<style>
menu {
	width: 100%%;
	box-sizing: border-box;
	position: relative;
	font-family: Verdana, Arial, Helvetica;
	font-size: small;
	font-weight: bold;
	overflow: hidden;
	border-radius: 18px;
	padding: 0 6px 8px;
	background: #3A7C8C;
}
#area {
	height: 28px;
	line-height: 28px;
	margin-left: 13px;
	color: #ccc;
}
#inner {
	border-radius: 12px;
	padding: 12px;
	background: #226474;
}
select {
	max-width: 100%%;
}
</style>
<menu>
	<div id="area">%Area%</div>
	<div id="inner">
